### ISSUE TITLE
[Bug]: unable to load gcc/10.1.0 compiler module on Cori 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#102]
### CDASH Build

https://my.cdash.org/test/58023286

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/serial/hello_c.yml

### Please describe the issue?

Unable to load `gcc/10.1.0` compiler module. We should update the buildtest configuration by either running `buildtest config compilers find`

We have this section for compiler definition under cori system https://github.com/buildtesters/buildtest-nersc/blob/devel/config.yml 

```
          gcc/10.1.0:
            cc: gcc
            cxx: g++
            fc: gfortran
            module:
              load:
              - gcc/10.1.0
              purge: false
```

### Relevant log output

```shell
gcc(3):ERROR:105: Unable to locate a modulefile for 'gcc/10.1.0'
```
```
