### ISSUE TITLE
[Bug]: spack version changed for E4S 21.05 on Cori

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#126]
### CDASH Build

https://my.cdash.org/test/61543397

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/spack/cori_spack_check.yml

### Please describe the issue?

Apparently our spack version has changed we used to have a regex expression

```
    status:
      regex:
        stream: stdout
        exp: "^(0.16.1-2806-16370e1b16)$"
```

According to output now we have

```
0.16.1
```

The test got a 0 returncode but failed on expression. It would be worth finding out how this test got changed? @wspear @eugeneswalker. 

Though we will be deleting this stack on Oct 31st according to our E4S support timeline https://docs.nersc.gov/applications/e4s/ 

### Relevant log output

```shell
0.16.1
```
