### ISSUE TITLE
[Bug]: spack version mismatch E4S/22.02 on Cori

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#127]
### CDASH Build

https://my.cdash.org/test/61543400

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/spack/cori_spack_check.yml

_No response_

### Please describe the issue?

There is a mismatch in the spack version. We have the following content for the buildspec and apparently spack has decided to change the hash. We have not updated the spack configuration, however we did see the expected version `0.17.1-1177-783615cacf` in the output when running `spack --version` and now its changed.
 
```
  e4s_22_02_spack:
    type: script
    executor: cori.local.bash
    tags: ["spack", "e4s"]
    description: Check e4s/21.05 spack instance
    run: |
      module load e4s/22.02
      spack --version
    status:
      regex:
        stream: stdout
        exp: "^(0.17.1-1177-783615cacf)$"
```

Testing this locally 
```
e4s:cori04> module load e4s/22.02
e4s:cori04> spack cd -r
e4s:cori04> git log --oneline -1
a260bf038d (HEAD -> e4s-22.02, origin/e4s-22.02) boost: fix v1.78 build with oneapi (#30463)
e4s:cori04> spack --version
0.17.1-1179-a260bf038d
```

It looks like that commit was two commits behind according to git log its not clear how this happened

```

commit a260bf038d765cdfece5b3d314aa921b035d3247 (HEAD -> e4s-22.02, origin/e4s-22.02)
Author: eugeneswalker <38933153+eugeneswalker@users.noreply.github.com>
Date:   Tue May 3 22:29:37 2022 -0700

    boost: fix v1.78 build with oneapi (#30463)

commit e0045a9daa64e17b7ba4dbbc2233b54b65fb10ed
Author: Sergey Kosukhin <sergey.kosukhin@mpimet.mpg.de>
Date:   Mon Apr 11 23:34:09 2022 +0200

    cray platform: unload cray-mpich (#29898)

commit 783615cacfdec7bd712cd903d409bcef6fc7cef4
Author: Tom Vander Aa <vanderaa@imec.be>
Date:   Mon Feb 14 21:23:35 2022 +0100

    intel-oneapi-mpi: set I_MPI_ROOT in setup_dependent_build_environment (#28890)

    * setting I_MPI_ROOT is sometimes needed for find_package(MPI) in cmake to work
```

According to https://github.com/spack/spack/commits/e4s-22.02 it looks like the commit we have is wrong not sure what happened. @eugenewalker have you seen this type of issue where post installation spack version gets changed? 

### Relevant log output

```shell
0.17.1-1179-a260bf038d
```
