### ISSUE TITLE
port stream test to Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#191]
Let's create an example test for stream in https://github.com/buildtesters/buildtest-nersc/blob/devel/.archive/apps/stream/stream.yml

Let's put this in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/benchmarks/

There is an example using `compilers` for running stream benchmark across multiple compilers let's try running the benchmark across `gcc` compilers

```yaml
buildspecs:
  stream_openmp_c:
    executor: generic.local.bash
    type: script
    description: "STREAM Microbenchmark C Test with OpenMP"
    tags: ["benchmark"]
    compilers:
      name: ['^(gcc)']
      default:
        gcc:
          cflags: -fopenmp -O2
          env:
           OMP_NUM_THREADS: 8
    run: |
      wget https://www.cs.virginia.edu/stream/FTP/Code/stream.c
      $BUILDTEST_CC $BUILDTEST_CFLAGS stream.c -o stream
      ./stream
```
